### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by brendenpelkie** [machineagency/science-jubilee#100]
### Steps:
1. Click link to documentation
2. Be sad there is no documentation
3.
....

### Snippet:

```python

// Paste your code here :)

```

**Comment by bsubbaraman** [comment]
I think this is from due to @sgbaird's ongoing updates and change to readthedocs (https://github.com/sgbaird/science-jubilee)! There are docs here https://science-jubilee.readthedocs.io though the formatting is funny right now

**Comment by sgbaird** [comment]
With the change from `science_jubilee` to `science-jubilee` that I suggested, the GitHub pages site went from https://machineagency.github.io/science_jubilee to https://machine agency.github.io/science-jubilee. Like @bsubbaraman mentioned, the plan is to shift to readthedocs. The PR will need to be merged. I will address some of this today.

**Comment by bsubbaraman** [comment]
ah of course, I forgot about the name change! Thanks, Sterling. I've updated the readme link and closed this for now, with more readthedocs changes coming soon!
