### ISSUE TITLE
Jubilee Aluminum Front Corner Brackets

### ISSUE THREAD

**Issue by yakavetsiv** [machineagency/science-jubilee#148]
### Feature enhancement details

I suggest adding the [Jubilee Aluminum Front Corner Brackets by Mandala Rose Works](https://www.filastruder.com/collections/jubilee/products/jubilee-aluminum-front-corner-brackets-by-mandala-rose-works) to the main Jubilee kit, along with the [Left Corner Spacer](https://github.com/machineagency/jubilee/blob/master/frame/upgrades/aluminum_corner_plates/fabrication_exports/3d_printed_parts/left_machined_corner_spacer.STL) and [Right Corner Spacer](https://github.com/machineagency/jubilee/blob/master/frame/upgrades/aluminum_corner_plates/fabrication_exports/3d_printed_parts/right_machined_corner_spacer.STL) in the main model repository. Additionally, please include 6x M5 buttonhead screws, 25mm long, with 6x M5 washers.

**Comment by brendenpelkie** [comment]
Good suggestion. We also like to build new machines with the aluminum Z yokes and motor plates to improve rigidity and solvent compatibility. I've added these recommendations as an option in the purchase guide with #156
