### ISSUE TITLE
Have you considered using readthedocs for hosting the website?

### ISSUE THREAD

**Issue by sgbaird** [machineagency/science-jubilee#83]
### Feature request details

This is my (opinionated) go-to, which has worked really well for me. Just wondering if you had considered this as an alternative to GitHub pages.

Some examples of ones I host there:
https://self-driving-lab-demo.readthedocs.io/
https://ac-training-lab.readthedocs.io/

**Comment by bsubbaraman** [comment]
This has been done! Thanks Sterling
