### ISSUE TITLE
Dead link for pipette tool wiring

### ISSUE THREAD

**Issue by sgbaird** [machineagency/science-jubilee#90]
### Steps to reproduce this bug

https://machineagency.github.io/science_jubilee/building/pipette_tool.html#pipette-tool links to https://github.com/machineagency/science_jubilee/blob/main/tool_library/OT2_pipette/assembly_docs/OT_Wiring_Diagram_V1.pdf

![image](https://github.com/machineagency/science_jubilee/assets/45469701/6099fee9-2692-46b7-8750-c1f97071d085)

Also, maybe worth linking to the build instructions tutorial from the POSE workshop?

**Comment by bsubbaraman** [comment]
The link was updated in the new docs!
