### ISSUE TITLE
Which build plate should I use for the lab automation deck?

### ISSUE THREAD

**Issue by sgbaird** [machineagency/science-jubilee#91]
### Topic

The heater version doesn't seem to be the right size.

https://machineagency.github.io/science_jubilee/building/lab_automation_deck.html#lab-automation-deck

Is this the one I should get? https://www.filastruder.com/products/jubilee-magbed-by-mandala-rose-works?pr_prod_strat=e5_desc&pr_rec_id=6ab6b9298&pr_rec_pid=4832673759303&pr_ref_pid=6681874595911&pr_seq=uniform

**Comment by bsubbaraman** [comment]
Thanks for sharing the process Sterling! Closing, feel free to re-open if there are still open questions about this
